<#
.SYNOPSIS
    Assemble a .asm file and re-emit its machine-code bytes as a MASM data source.

.DESCRIPTION
    Generic build utility for embedding one architecture's assembled code into another
    architecture's object.  Some assemblers can only target their own bitness — e.g. the
    x64 MASM (ml64.exe) cannot assemble x86 source — so a foreign-arch thunk can't be
    assembled directly into the native object.  This script bridges that:

      1. Assembles -SourceAsm with -AssemblerPath into a temporary object.
      2. Reads the size of the code (offset of -EndSymbol within -Section) and the
         section's raw bytes via dumpbin.
      3. Emits -OutputAsm: a *native*-MASM source that re-declares those bytes as read-only
         DB data, bracketed by the PUBLIC labels -BeginLabel / -EndLabel.  Assembling that
         output with the native assembler yields an object the native linker accepts, and
         (EndLabel - BeginLabel) recovers the original code size.

    The emitted bytes are position-independent data; this is only valid for code with no
    relocations (true for a self-contained, indirect-call-only thunk).

.NOTES
    Idempotent: unchanged input + args produce identical output.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string] $SourceAsm,      # .asm to assemble for its bytes
    [Parameter(Mandatory)] [string] $AssemblerPath,  # ml.exe / ml64.exe matching SourceAsm's arch
    [Parameter(Mandatory)] [string] $DumpbinPath,    # dumpbin.exe
    [Parameter(Mandatory)] [string] $OutputAsm,      # generated native-MASM data source
    [Parameter(Mandatory)] [string] $BeginLabel,     # PUBLIC label emitted at the first byte
    [Parameter(Mandatory)] [string] $EndLabel,       # PUBLIC label emitted one past the last byte
    [Parameter(Mandatory)] [string] $EndSymbol,      # symbol in SourceAsm whose offset = byte count
    [string] $Section = '.text$mn'                   # section holding the code
)

$ErrorActionPreference = 'Stop'

function Fail($msg) { Write-Error $msg; exit 1 }

if (-not (Test-Path -LiteralPath $SourceAsm))     { Fail "SourceAsm not found: $SourceAsm" }
if (-not (Test-Path -LiteralPath $AssemblerPath)) { Fail "AssemblerPath not found: $AssemblerPath" }
if (-not (Test-Path -LiteralPath $DumpbinPath))   { Fail "DumpbinPath not found: $DumpbinPath" }

$outDir = Split-Path -Parent $OutputAsm
if ($outDir -and -not (Test-Path -LiteralPath $outDir)) {
    New-Item -ItemType Directory -Force -Path $outDir | Out-Null
}

# --- 1. Assemble the source for its bytes (assemble-only; no link, no listing). ---
$tmpObj = [System.IO.Path]::ChangeExtension($OutputAsm, '.tmp.obj')
& $AssemblerPath -c -nologo "-Fo$tmpObj" $SourceAsm | Out-Null
if ($LASTEXITCODE -ne 0) { Fail "assembler failed ($LASTEXITCODE) on $SourceAsm" }

try {
    # --- 2a. Code size = section offset of EndSymbol (suffix match tolerates x86 '_'). ---
    $symLines = & $DumpbinPath -nologo -symbols $tmpObj
    if ($LASTEXITCODE -ne 0) { Fail "dumpbin -symbols failed ($LASTEXITCODE)" }

    $size = $null
    foreach ($line in $symLines) {
        # e.g. "008 0000003E SECT1  notype       External     | _InjectBootstrapThunkEnd"
        if ($line -match '\|\s*_?' + [regex]::Escape($EndSymbol) + '\s*$' -and
            $line -match '^\s*\S+\s+([0-9A-Fa-f]{8})\s') {
            $size = [Convert]::ToInt32($Matches[1], 16)
            break
        }
    }
    if ($null -eq $size) { Fail "end symbol '$EndSymbol' not found in $SourceAsm object" }
    if ($size -le 0)     { Fail "end symbol '$EndSymbol' has non-positive offset ($size)" }

    # --- 2b. Raw section bytes. ---
    $rawLines = & $DumpbinPath -nologo "-SECTION:$Section" -RAWDATA:BYTES $tmpObj
    if ($LASTEXITCODE -ne 0) { Fail "dumpbin -RAWDATA failed ($LASTEXITCODE)" }

    $bytes = New-Object System.Collections.Generic.List[string]
    foreach ($line in $rawLines) {
        # "  00000000: 55 8B EC 53 ... 6A  U.<S.....j"  -> capture the leading hex run only.
        $afterColon = ($line -split ':', 2)
        if ($afterColon.Count -lt 2) { continue }
        if ($afterColon[1] -match '^\s*((?:[0-9A-Fa-f]{2} )*[0-9A-Fa-f]{2})') {
            foreach ($b in ($Matches[1].Trim() -split '\s+')) { $bytes.Add($b) }
        }
    }
    if ($bytes.Count -lt $size) {
        Fail "extracted $($bytes.Count) bytes from $Section but need $size"
    }

    # --- 3. Emit native-MASM read-only data with the chosen PUBLIC labels. ---
    $srcName = Split-Path -Leaf $SourceAsm
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("; AUTO-GENERATED by utils/Asm-To-MasmDataBlob.ps1 from $srcName -- DO NOT EDIT.")
    [void]$sb.AppendLine("; $size bytes of position-independent code, embedded as data.")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('.const')
    [void]$sb.AppendLine("PUBLIC $BeginLabel")
    [void]$sb.AppendLine("PUBLIC $EndLabel")
    [void]$sb.AppendLine("$BeginLabel LABEL BYTE")
    for ($i = 0; $i -lt $size; $i += 16) {
        $chunk = for ($j = $i; $j -lt [Math]::Min($i + 16, $size); $j++) { '0' + $bytes[$j] + 'h' }
        [void]$sb.AppendLine('    DB ' + ($chunk -join ','))
    }
    [void]$sb.AppendLine("$EndLabel LABEL BYTE")
    [void]$sb.AppendLine('END')

    # UTF-8 without BOM (ml64 chokes on a BOM).
    [System.IO.File]::WriteAllText($OutputAsm, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
}
finally {
    Remove-Item -LiteralPath $tmpObj -ErrorAction SilentlyContinue
}
